[nfs]
172.31.3.172 ansible_ssh_user='ec2-user'

[webservers]
172.31.14.40 ansible_ssh_user='ec2-user'
<Web-Server2-Private-IP-Address> ansible_ssh_user='ec2-user'

[db]
172.31.0.10 ansible_ssh_user='ubuntu' 

[lb]
172.31.22.59 ansible_ssh_user='ubuntu'