[uat-webservers]
172.31.34.146 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=obafema-ec2.pem
172.31.46.109 ansible_ssh_user='ec2-user' ansible_ssh_private_key_file=obafema-ec2.pem

[lb]
172.31.27.118 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=obafema-ec2.pem
172.31.22.59 ansible_ssh_user='ubuntu' ansible_ssh_private_key_file=obafema-ec2.pem